apiVersion: v1
kind: Service
metadata:
  name: nodeopsx-service
  labels:
    app: nodeopsx
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "3000"
spec:
  selector:
    app: nodeopsx
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
